# Generated by Django 3.1.4 on 2020-12-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201214_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
